CircleCI: go back to debian-11, but add bullseye-backport and install swtpm swtpm and golang 1.19 from there. Duplicate the apt line to be a copy paste of each other to reduce local host install inssues from users taking CircleCI as guideline
Otherwise, building on debian bookwork cause coreboot for power to fail at https://app.circleci.com/pipelines/github/tlaurion/heads/1637/workflows/8b99e5a2-23ad-4947-a9c3-7890e8dc5e75/jobs/21848
libstb/create-container.c: In function 'getPublicKeyRaw':
libstb/create-container.c:85:17: error: 'EVP_PKEY_get1_EC_KEY' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   85 |                 key = EVP_PKEY_get1_EC_KEY(pkey);
      |                 ^~~
In file included from libstb/create-container.c:26:
/usr/include/openssl/evp.h:1374:19: note: declared here
 1374 | struct ec_key_st *EVP_PKEY_get1_EC_KEY(EVP_PKEY *pkey);
      |                   ^~~~~~~~~~~~~~~~~~~~
libstb/create-container.c:89:17: error: 'EC_KEY_get0_group' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   89 |                 ecgrp = EC_KEY_get0_group(key);
      |                 ^~~~~
In file included from libstb/create-container.c:24:
/usr/include/openssl/ec.h:1034:39: note: declared here
 1034 | OSSL_DEPRECATEDIN_3_0 const EC_GROUP *EC_KEY_get0_group(const EC_KEY *key);
      |                                       ^~~~~~~~~~~~~~~~~
libstb/create-container.c:93:17: error: 'EC_KEY_get0_public_key' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   93 |                 ecpoint = EC_KEY_get0_public_key(key);
      |                 ^~~~~~~
/usr/include/openssl/ec.h:1062:39: note: declared here
 1062 | OSSL_DEPRECATEDIN_3_0 const EC_POINT *EC_KEY_get0_public_key(const EC_KEY *key);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~
libstb/create-container.c:97:17: error: 'EC_POINT_point2bn' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
   97 |                 pubkeyBN = EC_POINT_point2bn(ecgrp, ecpoint, POINT_CONVERSION_UNCOMPRESSED,
      |                 ^~~~~~~~
/usr/include/openssl/ec.h:770:31: note: declared here
  770 | OSSL_DEPRECATEDIN_3_0 BIGNUM *EC_POINT_point2bn(const EC_GROUP *,
      |                               ^~~~~~~~~~~~~~~~~
libstb/create-container.c:102:17: error: 'EC_KEY_free' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  102 |                 EC_KEY_free(key);
      |                 ^~~~~~~~~~~
/usr/include/openssl/ec.h:1003:28: note: declared here
 1003 | OSSL_DEPRECATEDIN_3_0 void EC_KEY_free(EC_KEY *key);
      |                            ^~~~~~~~~~~
/root/project/crossgcc/ppc64/bin/powerpc64le-linux-musl-gcc        -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/include -Iinclude -MMD -include /root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/include/config.h -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libfdt -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libflash -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libxz -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libc/include -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libpore -D__SKIBOOT__ -nostdinc -isystem /root/project/crossgcc/ppc64/bin/../lib/gcc/powerpc64le-linux-musl/8.3.0/include -DBITS_PER_LONG=64 -DHAVE_BIG_ENDIAN -ffreestanding -DHAS_STACK_PROT -fno-strict-aliasing -pie -fpie -fno-pic -mbig-endian -m64 -fno-asynchronous-unwind-tables -mcpu=power7 -Wl,--oformat,elf64-powerpc -ggdb -ffixed-r13 -std=gnu11 -mabi=elfv1 -DUSE_VALGRIND=1 -mstack-protector-guard=tls -mstack-protector-guard-reg=r13 -mstack-protector-guard-offset=0 -fstack-protector -fstack-protector-strong -Wjump-misses-init -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wstack-usage=1024 -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wno-pointer-sign -Wextra -Wno-sign-compare -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wcast-align -Winit-self -Werror -Wframe-larger-than=1024 -Os -g -msoft-float -mno-string -mno-multiple -mno-vsx -mno-altivec  -c core/chip.c -o core/chip.o
cc1: all warnings being treated as errors
/root/project/crossgcc/ppc64/bin/powerpc64le-linux-musl-gcc        -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/include -Iinclude -MMD -include /root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/include/config.h -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libfdt -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libflash -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libxz -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libc/include -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot -I/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libpore -D__SKIBOOT__ -nostdinc -isystem /root/project/crossgcc/ppc64/bin/../lib/gcc/powerpc64le-linux-musl/8.3.0/include -DBITS_PER_LONG=64 -DHAVE_BIG_ENDIAN -ffreestanding -DHAS_STACK_PROT -fno-strict-aliasing -pie -fpie -fno-pic -mbig-endian -m64 -fno-asynchronous-unwind-tables -mcpu=power7 -Wl,--oformat,elf64-powerpc -ggdb -ffixed-r13 -std=gnu11 -mabi=elfv1 -DUSE_VALGRIND=1 -mstack-protector-guard=tls -mstack-protector-guard-reg=r13 -mstack-protector-guard-offset=0 -fstack-protector -fstack-protector-strong -Wjump-misses-init -Wsuggest-attribute=const -Wsuggest-attribute=noreturn -Wstack-usage=1024 -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -Werror-implicit-function-declaration -Wdeclaration-after-statement -Wno-pointer-sign -Wextra -Wno-sign-compare -Wmissing-prototypes -Wmissing-declarations -Wwrite-strings -Wcast-align -Winit-self -Werror -Wframe-larger-than=1024 -Os -g -msoft-float -mno-string -mno-multiple -mno-vsx -mno-altivec  -c core/init.c -o core/init.o
libstb/container-utils.c: In function 'isValidHex':
libstb/container-utils.c:89:39: error: '%d' directive writing between 1 and 10 bytes into a region of size 7 [-Werror=format-overflow=]
   89 |                 sprintf(multiplier, "{%d}", len * 2); // allow this (byte) len only
      |                                       ^~
libstb/container-utils.c:89:37: note: directive argument in the range [2, 2147483647]
   89 |                 sprintf(multiplier, "{%d}", len * 2); // allow this (byte) len only
      |                                     ^~~~~~
libstb/container-utils.c:89:17: note: 'sprintf' output between 4 and 13 bytes into a destination of size 8
   89 |                 sprintf(multiplier, "{%d}", len * 2); // allow this (byte) len only
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libstb/container-utils.c: In function 'isValidAscii':
libstb/container-utils.c:123:40: error: '%d' directive writing between 1 and 10 bytes into a region of size 6 [-Werror=format-overflow=]
  123 |                 sprintf(multiplier, "{,%d}", len);  // allow *up to* this len
      |                                        ^~
libstb/container-utils.c:123:37: note: directive argument in the range [1, 2147483647]
  123 |                 sprintf(multiplier, "{,%d}", len);  // allow *up to* this len
      |                                     ^~~~~~~
libstb/container-utils.c:123:17: note: 'sprintf' output between 5 and 14 bytes into a destination of size 8
  123 |                 sprintf(multiplier, "{,%d}", len);  // allow *up to* this len
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[3]: *** [/root/project/build/ppc64/coreboot-git/payloads/external/skiboot/skiboot/libstb/Makefile.inc:18: libstb/create-container] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:17: /root/project/build/ppc64/coreboot-git/payloads/external/skiboot/build/skiboot.elf] Error 2
make[1]: *** [payloads/external/Makefile.inc:377: payloads/external/skiboot/build/skiboot.elf] Error 2
make[1]: Leaving directory '/root/project/build/ppc64/coreboot-git'
tail /root/project/build/ppc64/log/coreboot.log

We also bumped linux kernel to 5.10.178 in prior commit: Talos II will fail there as well with newer buildstack...